0xERR0R/blocky

docs/README.md

Add info to docs about installing with helm

---

.gitignore
Makefile
cmd/serve.go
config/config.go
docs/README.md
metrics/metrics.go
resolver/mocks.go
resolver/upstream_resolver_test.go
server/server.go
server/server_endpoints.go
server/server_test.go

DoH server support

---

config/config.go
docs/configuration.md
resolver/ipv6_checker.go
resolver/ipv6_checker_test.go
resolver/upstream_resolver.go
server/server.go

Scenes like this https://github.com/AdguardTeam/AdGuardHome/issues/473
Also my network have no IPv6 internet but blocky receive lots AAAA query, i hope to ignore these queries

Add support of disbale ipv6(AAAA) query

---

lists/list_cache.go
lists/list_cache_test.go

Fix panic with empty query 

---

docs/installation.md

chore(docs): Update link to kubernetes chart

---

api/api_suite_test.go
cmd/root.go
cmd/serve.go
config/config.go
config/config_suite_test.go
lists/list_suite_test.go
log/logger.go
resolver/resolver_suite_test.go
server/server.go
server/server_suite_test.go
stats/stats_suite_test.go
util/util_suite_test.go

Adds config option to send to the logger and set default to true, making it work exactly the same by default unless you set to false.  #182

#182 -  added config option for logTimestamp

---

resolver/caching_resolver.go
resolver/caching_resolver_test.go
util/common.go
util/common_test.go

Make cache for all query types

---

config/config.go
docs/config.yml
docs/configuration.md
resolver/caching_resolver.go
resolver/caching_resolver_test.go

add prefetchExpires and prefetchThreshold option (instead of constant value)

Make prefetch fully configurable

---

docs/configuration.md

Adjusted spacing in the yaml example

Update documentation example for Client Groups

---

cmd/root.go
cmd/serve.go
cmd/serve_test.go
config/config.go
config/config_test.go
resolver/upstream_resolver.go
util/bootstrap.go

bootstrapDNS not used for upstream DNS resolution (#242)

---

docs/config.yml
docs/configuration.md
lists/list_cache.go
lists/list_cache_test.go

inline lists definition (#207)

---

docs/blocky-query-grafana_modified.json

Hi Dimitri, it's just a slightly modified version of your dashboard. I've changed the client filter to "multi select", added an overview of BLOCKED requests by group and changed the "query count by client" from "pie chart" to "bar gauge".

slightly modified version of Dimitri's dasboard

---

config/config.go
docs/config.yml
docs/configuration.md
docs/includes/abbreviations.md
lists/list_cache.go
lists/list_cache_test.go
resolver/blocking_resolver.go

configurable list download timeout

---

config/config.go
docs/config.yml
docs/configuration.md
lists/list_cache.go
lists/list_cache_test.go
resolver/upstream_resolver.go

Configurable upstream lookup timeout (#256)

---

querylog/logger_writer.go

added missing field in query log (#291)

---

config/config.go
config/config_test.go

Ipv6 parsing error in upstream definition (#285)

---

config/config.go
config/config_test.go
docs/config.yml
docs/configuration.md
server/server.go

DoT (DNS-over-TLS) server (#303)

---

.github/workflows/development-docker.yml

Docker image vulnerability scan with grype

---

docs/configuration.md

There's something wrong with the old one, there are inconsistent and broken indent in it 😅

Fix the indent of yaml code block in docs/configuration.md

---

resolver/blocking_resolver_test.go
resolver/caching_resolver_test.go

test: added additional assertions, introduced channels for bus event tests, refactoring

some test improvements

---

config/config.go
lists/downloader.go
lists/downloader_test.go
lists/list_cache.go
lists/list_cache_test.go
resolver/blocking_resolver.go

Some code clean up, extracting download functionality to the separate file/struct

refactoring list cache

---

resolver/upstream_resolver.go

I'm newbie to Go, please help verify the patch, thanks!
close #446

Hide DoH client http header "User-Agent"

---

server/server.go

This is a #520 follow-up PR. Also fixes #517.

Use same minimum TLS version & cipher for DoH server as DoT server

---

Makefile
config/config.go

Fix race condition in test

---

api/api_endpoints.go
api/api_endpoints_test.go
helpertest/helper.go
server/server_endpoints.go
server/server_test.go

set content-type header for HTTP endpoints

---

querylog/database_writer.go

Adds new PK column "id" for mysql/mariadb and postgres
closes #585

Add primary key to the query log table

---

.github/workflows/ci-build.yml
.github/workflows/golangci-lint.yml
.github/workflows/release.yml
Dockerfile

Define golang version only in go.mod (#618)

---

.github/workflows/ci-build.yml

https://docs.codecov.com/docs/github-2-getting-a-codecov-account-and-uploading-coverage#github-actions

chore: switch to codecov GitHub Action

---

.github/workflows/close_stale.yml

add https://github.com/marketplace/actions/close-stale-issues

add stale action

---

config/config.go
docs/config.yml
docs/configuration.md
go.mod
go.sum
resolver/hosts_file_resolver.go
resolver/hosts_file_resolver_test.go

Filter loopback addresses from hosts file

---

server/server.go

When I authored #532, I decided to use RSA certificates for increased compatibility. This takes quite a while, particularly on slower platforms, such as ARM based SoCs. The slow speed also affects development in the `server` package, especially if IDE is configured to run tests on every save - these take about 8-9 seconds on my fairly modern development machine.
Any DNS client supporting DoT or DoH will be relatively modern by design (RFCs dated 2016 and 2018, respectively), so they should support ECDSA certificates, which have been supported in OpenSSL for more than a decade.

Change self-signed cert to ECDSA

---

.github/workflows/development-docker.yml

switch between CR_PAT & GITHUB_TOKEN for github registry login

Fb workflow fix permission

---

main_static.go

fix: add timezone data to docker container

---

config/config.go
docs/config.yml
docs/configuration.md
redis/redis.go

Added redis sentinal feature.
Closes #632

[Feature]: Support for redis sentinel(#632)

---

redis/redis.go
redis/redis_test.go

- added some test cases to improve the code coverage
- restructured ginkgo test (added some when/by)
- removed redundant log statements from code

Improvements redis test

---

.golangci.yml
cache/stringcache/string_caches_benchmark_test.go
cmd/root.go
config/config.go
evt/events.go
helpertest/helper.go
lists/list_cache_test.go
log/logger.go
metrics/metrics.go
redis/redis.go
resolver/blocking_resolver.go
resolver/bootstrap.go
resolver/bootstrap_test.go
resolver/hosts_file_resolver.go
resolver/hosts_file_resolver_test.go
resolver/noop_resolver.go
resolver/query_logging_resolver.go
resolver/rewriter_resolver.go
resolver/upstream_resolver.go
resolver/upstream_resolver_test.go
server/server.go

added:
- nolintlint
- usestdlibvars
removed unused lint suppressions

chore(build): add additional linters

---

resolver/ede_resolver.go
resolver/ede_resolver_test.go

fix(ede-resolver): don't panic when next resolver errors

---

go.mod
go.sum
querylog/database_writer.go
querylog/database_writer_test.go

DB writer writes max. 100 entries in bulk now
closes #733

feat: reduce bulk size in database writer (#733)

---

lists/list_cache_test.go
resolver/blocking_resolver.go
resolver/blocking_resolver_test.go
resolver/caching_resolver.go
resolver/caching_resolver_test.go
resolver/client_names_resolver.go
resolver/client_names_resolver_test.go
resolver/conditional_upstream_resolver.go
resolver/conditional_upstream_resolver_test.go
resolver/custom_dns_resolver.go
resolver/custom_dns_resolver_test.go
resolver/ede_resolver.go
resolver/ede_resolver_test.go
resolver/filtering_resolver.go
resolver/filtering_resolver_test.go
resolver/fqdn_only_resolver.go
resolver/fqdn_only_resolver_test.go
resolver/hosts_file_resolver.go
resolver/hosts_file_resolver_test.go
resolver/metrics_resolver.go
resolver/resolver.go
resolver/sudn_resolver.go
resolver/sudn_resolver_test.go
resolver/upstream_resolver.go
resolver/upstream_resolver_test.go

Also includes #781 so the CI passes here.

style(resolver): standardize configuration disabled implementations and tests

---

resolver/blocking_resolver_test.go
resolver/bootstrap.go
resolver/bootstrap_test.go
resolver/mocks_test.go

fix: `connectIPVersion` not being respected for upstream connections

---

Makefile
api/api.go
go.mod
go.sum
server/server.go

Updated to the latest golangci-lint version

chore(build): update golangci-lint

---

e2e/containers.go
e2e/e2e_suite_test.go

- set default timeout for eventually
- add HTTP listener readiness check for blocky container

Improve e2e tests

---

go.mod
go.sum
lists/parsers/hosts.go
lists/parsers/hosts_test.go

fix: make domain validation in list parser more lenient

---

.github/workflows/release.yml

see https://goreleaser.com/deprecations/#-rm-dist

chore(build): change deprecated "rm-dist" flag to "clean"

---

resolver/caching_resolver.go
resolver/caching_resolver_test.go

fix: don't cache EDNS pseudo records

---

Makefile
resolver/blocking_resolver.go
resolver/caching_resolver.go

- fixed race conditions
- set timeout for e2e pipeline (sometimes testcontainers waits 1h for container termination)
- set 1 retry for flaky tests

Test improvements

---

util/common_test.go

need to merged before #1153 
Test fails with dns 1.1.56

chore(text): fix ipv6 representation

---

cmd/serve.go
cmd/serve_test.go
e2e/basic_test.go
e2e/blocking_test.go

fix: return error code on server starup failure (#1165)

---

resolver/caching_resolver.go
resolver/caching_resolver_test.go

Don't cache responses with CD (Checking Disabled) flag (DNSSEC)
closes #455

fix: don't cache DNS responses with CD flag

---

.devcontainer/devcontainer.json

removes explicit go version in devcontainer config

remove go version in devcontainer file

---

Dockerfile

Moved most Zig logic to another image since I also use it in other projects: https://github.com/kwitsch/ziggoimg
Bonus: decreased build time on second run.

Dockerfile streamline

---

querylog/database_writer_test.go

I have seen sporadic errors in this test (only on slow environments). I was able to reproduce the error: it is due to the fact that the changes from the DB migration (creation of tables etc) may become "visible" to other sessions a bit later. The first write attempt (insert into the table) goes wrong.
This fix sets the number of connections to 1 and forces the db consumer to reuse the same db connection

chore: improve database writer tests

---

Dockerfile

Fixed and added opencontainer labels in accordance to: https://github.com/opencontainers/image-spec/blob/main/annotations.md

opencontainer labels

---

docs/prometheus_grafana.md

See https://github.com/0xERR0R/blocky/discussions/1116

fix(docs): clarify `blocky_error_total`

---

.golangci.yml
e2e/basic_test.go
e2e/blocking_test.go
e2e/containers.go
e2e/e2e_suite_test.go
e2e/metrics_test.go
e2e/querylog_test.go
e2e/redis_test.go
e2e/upstream_test.go
lists/downloader.go
lists/downloader_test.go
lists/list_cache.go
lists/list_cache_test.go
lists/sourcereader.go
resolver/hosts_file_resolver.go

Changes:
- enabled context linters
- made e2e-tests use ginkgo context
- made file downloader context aware
- fixed linter findings
Part of #1264

Refactoring: FileDownloader

---

resolver/rewriter_resolver.go
resolver/rewriter_resolver_test.go

Apparently Tailscale's magic DNS does this.
Fixes #1311

fix(rewrite): support the case where upstream doesn't echo the question

---

querylog/file_writer.go

fix: Parse time from file names in the local system timezone

---

.github/workflows/docs.yml
README.md
cmd/root_test.go
config/blocking.go
config/blocking_test.go
config/config_test.go
docs/additional_information.md
docs/api/openapi.yaml
docs/blocky-grafana.json
docs/blocky-query-grafana-postgres.json
docs/blocky-query-grafana.json
docs/config.yml
docs/configuration.md
docs/index.md
docs/installation.md
docs/interfaces.md
docs/prometheus_grafana.md
e2e/blocking_test.go
e2e/metrics_test.go
lists/list_cache.go
lists/list_cache_benchmark_test.go
lists/list_cache_enum.go
lists/list_cache_test.go
metrics/metrics_event_publisher.go
resolver/blocking_resolver.go
resolver/blocking_resolver_test.go
server/server_test.go

feat: update list config and code to use "allow/deny" language

---

config/custom_dns.go
config/custom_dns_test.go

fix: configuration error if customDNS.mappings contains multiple entries with whitespace

---

Dockerfile
go.mod
go.sum
main_static.go

- update golang
- add rootcerts
- simplify Dockerfile

chore(build): refactor Dockerfile

---

docs/additional_information.md

Fixes: #1700
- Accidentally removes redundant white-spaces as well?

fix(docs): fix stale link in example Allowlists (#1700)

---

server/server_endpoints.go
server/server_test.go

feat: add "cache-control" http header to DoH response

---

docs/configuration.md

Reworded this section to be a little more clear.

grammar/wording of filter section in configuration.md

---

docs/installation.md

docs: fix typo and trailing whitespace

---

config/config.go
docs/config.yml
docs/configuration.md
e2e/doh_test.go
server/server.go
server/server_endpoints.go
server/server_test.go

feat: make DoH query path configurable

---

e2e/basic_test.go
server/server_endpoints.go
web/index.go
web/robots.txt

feat: add robots.txt
