0xERR0R/blocky

docs/blocky-grafana.json
When running multiple instances of blocky and emitting metrics to prometheus, the grafana dashboard will have trouble when prometheus has multiple instances of blocky collected.
This pull request will remedy some of the problematic queries to properly handle multiple instances.
For example, with 3 instances of blocky running and emitting metrics the proposed changes shows this:
Running just one instance with the proposed changes shows this:
=> Support multiple instances of blocky

docs/README.md
Current refreshPeriod example sets refresh to 1 minute. This results in DNS queries failing during Blocky reload 4 seconds of every minute.
=> Update README for correct refreshPeriod

docs/README.md
Awesome little DNS proxy!  This just adds a line in the Dockerfile to allow Prometheus to pull stats.
=> Dockerfile for adding Prom. access.

cmd/root.go
By default, logrus outputs to `stderr`. Other than being semantically incorrect for the output generated, it also makes it hard to grep through the output as `stderr` messages aren't filtered by grep.
=> Log output to stdout instead of stderr

docs/README.md
This is the new location of the helm chart.
=> fix: links to blocky helm chart

server/server.go
When starting blocky via `NewServer` the loglevel isn't parsed and set unlike when starting it via `root.go`
=> set loglevel on new

api/api_suite_test.go, cmd/blocking.go, cmd/cmd_suite_test.go, cmd/query.go, cmd/root.go, cmd/serve.go, config/config.go, config/config_suite_test.go, helpertest/helper.go, lists/list_cache.go, lists/list_suite_test.go, log/logger.go, resolver/blocking_resolver.go, resolver/query_logging_resolver_test.go, resolver/resolver.go, resolver/resolver_suite_test.go, server/server.go, server/server_suite_test.go, stats/stats_suite_test.go, util/common.go, util/common_test.go, util/util_suite_test.go
Created internal logger instance so that it doesn't interfere with the users global instance when used as a package. This was very annoying for us since we wanted our code to have debug level but that would also set blocky's log level which is too verbose and not relevant for us.
Seems like there are some test are failing. Not too sure how to fix them.
=> use package logger instance instead of global logrus instance

server/server.go, server/server_test.go, testdata/doubleclick.net.txt
We should check ads before query conditional upstream.
e.g. I mapped "cn" ccTLD to ISP provided DNS, defaults use Google DNS, but also expect ads can be blocked.
=> Blocking with conditional upstream

Dockerfile
Hi :wave: Small change here. I created an `ENTRYPOINT` with [tini](https://github.com/krallin/tini) and updated the `CMD` in the `Dockerfile`. tini is already included in the `Docker` CRI, however some people (like me) use a different CRI like `containerd` or `cri-o` where we don't have access to an `--init` flag. 
`tini` also has other benefits as described in this [Github issue](https://github.com/krallin/tini/issues/8#issuecomment-146135930).
=> feat(docker): add tini to container image

evt/events.go, metrics/metrics_event_publisher.go, resolver/caching_resolver.go, resolver/caching_resolver_test.go
Prefetch hit ratio = `blocky_prefetch_hit_count / blocky_cache_hit_count`
#189
=> Add prefetch hit metrics

docs/configuration.md
Expand the description of the port variable in the config md as it is not obvious currently that it can be used to specify IP and not just port.
=> note how to listen on a specific IP

resolver/blocking_resolver.go, resolver/blocking_resolver_test.go
WhitelistOnly is only used, if no more than two whitelists are available or all clients include all whitelists. 
Look at the following config snippet. Two Groups are defined, each with their own set of "whitelist" entries. 
```yaml
blocking:
whiteLists:
net_one:
- net_one_whitelist.txt
net_two:
- net_two_whitelist.txt
clientGroupsBlock:
one-client*:
- net_one
two-client*:
- net_two
clientLookup:
clients:
one-client-1:  [127.0.0.1]
two-client-2:  [127.0.0.2]
```
If multiple WhitelistOnly groups are defined, then every client, which do NOT include ALL whitelists, can resolve non-whitelist items. 
The `reflect.DeepEqual()` list now contains the check if `[net_one] ==  [net_one, net_two]`, which will always return false.  
**Expected Behavior**: Both clients are restricted to the defined …
=> WhitelistOnly Fix for multiple entries

docs/installation.md
Before blocky complained about:
```
[2021-06-25 10:10:20]  WARN parallel_best_resolver: using deprecated 'externalResolvers' as default upstream resolver configuration name, please consider to change it to 'default'
```
=> Update installation doc with change of depreacted externalResolvers

docs/configuration.md
If `udp:x.y.z.w` or `tcp:x.y.z.w` is used as a resolver, a warning is recorded upon startup:
```
[2021-08-10 22:32:22]  WARN net prefix udp is deprecated, using tcp+udp as default fallback
```
Standalone use of `tcp` or `udp` alone with resolvers seemed to have been deprecated, so I have changed documentation to reflect this.
=> Docs change with udp and tcp deprecation

config/config.go, docs/configuration.md, resolver/blocking_resolver.go, resolver/blocking_resolver_test.go
When an address is blocked, it can be cached by the client. If we
then wish to allow that address, or just disable the blocking
feature, that client is not gonna be able to see that domain until
the previous domain expires.
The units of time for this setting is in seconds, since we might
want to set it to values around 5 or 10 seconds, depending on the
scenario. The default value for it is the value used before, so
ignoring this setting wont result on any change.
Wasn't sure about the names to use, so make sure you comment
if you have some better examples or comment regarding that or
anything else!
=> Allow configuration of block time

Dockerfile
=> Suppress health check output

resolver/stats_resolver_trigger.go, server/server_config_trigger.go
It took me a bit to make the `golangci-lint` tool work on my end, but it seems like using the new format fixes the issues.
=> Change golang build constraint syntax

config/config.go, config/config_test.go, docs/config.yml, docs/configuration.md, docs/includes/abbreviations.md, lists/list_cache.go, mkdocs.yml, resolver/blocking_resolver.go, resolver/blocking_resolver_test.go, resolver/caching_resolver.go, resolver/caching_resolver_test.go, testdata/config.yml
=> Change configuration format for duration (#263)

.golangci.yml, README.md, docs/config.yml, docs/configuration.md, docs/includes/abbreviations.md, docs/index.md, lists/caches.go, lists/caches_test.go, lists/list_cache.go, lists/list_cache_test.go
=> regex support for matching (#12)

Dockerfile
* Updates Alpine version
* Install tzdata and ca-certificates in the final image
I'm not certain why installing tzdata or ca-certificates was excluded and replaced by copying from the build container. Any thoughts @0xERR0R ?
=> chore(docker): Update alpine version

config/config.go, config/config_enum.go, docs/configuration.md, querylog/none_writer.go, resolver/query_logging_resolver.go
This implements the option to disable query logging, as requested in #333. A new `NoneWriter` is implemented, which requires almost no change in code to implement the new feature.
The default behaviour is unchanged; if there is no `queryLog` configured, the output is to console. To disable query logging, the following configuration is required:
```
queryLog:
type: none
```
Documentation has been modified to reflect the changes.
=> Implemented the option to disable query logging

querylog/database_writer.go, querylog/database_writer_test.go, querylog/file_writer.go, querylog/file_writer_test.go, resolver/query_logging_resolver.go, resolver/query_logging_resolver_test.go
If mysql or file query log can't be initialized (wrong parameter, no connection, wrong directory...), blocky should start and use console as fallback.
Closes #318
=> Fallback when using mysql or file as query log (#318)

resolver/blocking_resolver.go, resolver/blocking_resolver_test.go
different client names for the same group
=> Define different client names for the same group (#251)

config/config.go, docs/configuration.md, lists/list_cache.go, lists/list_cache_test.go, resolver/blocking_resolver.go
New configuration options:
- blocking.downloadAttempts
- blocking.downloadCooldown
=> Make retry for list download configurable (#308)

server/server_config_trigger.go
#267 broke building on older go versions. This fixes it.
I also made sure it still builds with 1.17.
=> Make go:build compatible with go 1.16

config/config.go, docs/config.yml, docs/configuration.md, resolver/custom_dns_resolver.go, resolver/custom_dns_resolver_test.go, server/server_test.go
I changed the tests to use a random but common TTL on each run. Maybe you'd prefer a separate test for the TTL explicitly.
Also, I haven't updated the docs.
=> Allow configuring custom DNS TTL

cmd/root.go, config/config.go, config/config_test.go, docs/config.yml, docs/configuration.md, resolver/client_names_resolver.go, server/server.go, server/server_test.go, testdata/config.yml
I use this to bind to localhost and my LAN interface, but not the WAN one.
=>  Allow configuring multiple listen addresses for each port

docs/blocky-grafana.json
This update would update all of the data inputs and sources to be compatible with newer versions of Grafana. 
- Updated Pie charts to use the new Pie Charts plugin
- Updated Time Series to use the new Time Series plugin
- Updated stat panels to use Table instead of Time Series for input
=> fix: update dashboard for new grafana versions

web/index.go, web/index.html
I have embedded `index.go` with `go:embed`, as requested in #374.
=> Embedded index.go with go:embed

docs/prometheus_grafana.md, evt/events.go, lists/list_cache.go, lists/list_cache_test.go, metrics/metrics_event_publisher.go
This implements #309 . Adds `blocky_failed_download_count` Prometheus metric, which increments the counter for every failed attempt to download a blocking list.
=> Add failed_download_count metric

.github/workflows/development-docker.yml
=> Do not run docker build on fork

docs/config.yml
default for `tlsPort` is 853, hence adjusting the (commented out) example
=> docs/config.yml: default for tlsPort is 853

README.md, config/config.go, docs/config.yml, docs/configuration.md, resolver/blocking_resolver.go, resolver/blocking_resolver_test.go, resolver/caching_resolver_test.go, resolver/client_names_resolver_test.go, resolver/conditional_upstream_resolver.go, resolver/conditional_upstream_resolver_test.go, resolver/conditionall_upstream_resolver.go, resolver/custom_dns_resolver.go, resolver/custom_dns_resolver_test.go, resolver/hosts_file_resolver_test.go, resolver/ipv6_disabling_resolver_test.go, resolver/metrics_resolver_test.go, resolver/mocks.go, resolver/noop_resolver.go, resolver/noop_resolver_test.go, resolver/parallel_best_resolver.go, resolver/parallel_best_resolver_test.go, resolver/query_logging_resolver_test.go, resolver/resolver.go, resolver/resolver_test.go, resolver/rewriter_resolver.go, resolver/rewriter_resolver_test.go, server/server.go
Main commit message:
> This commit extracts rewriting logic from `ConditionalUpstreamResolver`
> into the new `RewriterResolver`, and uses that to enable rewriting for
> the `CustomDNSResolver`.
> `RewriterResolver` wraps a resolver and applies the rewrite to the
> request that is forwarded to the inner resolver.
> 
> It also introduces a new optional interface: `NamedResolver`.
> This allows a `Resolver` to choose what its user friendly name is,
> instead of always being its type name.
I use this feature to have an alternative way of spelling my domain which is a bit long.
Comes in handy when manually poking around.
Also did some smaller changes to tests such as unifying `MockResolver` and `resolverMock`.
=> Add rewrite support to custom DNS

Dockerfile
After further testing, defaulting was not correctly occurring. Switching to env var expansion with embedded default value.
=> Fixing unexpanded CMD variable with correct defaulting behavior.

docs/config.yml
To prevent the warning:
> net prefix tcp is deprecated, using tcp+udp as default fallback
=> Update reference configuration file in the docs

docs/configuration.md
Just like the default value `List refresh period` is also mentioned below, it'll be more friendly for the users ;)
=> Add default Block TTL information in the docs

server/server_endpoints.go
Just a small change so the link to Swagger is versioned.
=> Change swagger URL to match blocky's version

docs/index.md
This rectifies the improperly aligned points on the mkdocs index page and normalises the formatting.
=> Indent "Integration" sub-points on mkdocs index page

cache/stringcache/string_caches.go, cache/stringcache/string_caches_benchmark_test.go, cache/stringcache/string_caches_test.go, util/common.go, util/common_test.go
- removed temporary map which was used to eliminate duplicates
- removed temporary step to create a sorted slice
Benchmark before/after:
```
BenchmarkStringCache-16   282   4215279 ns/op   2319853 B/op   10862 allocs/op
BenchmarkStringCache-16   310   3751947 ns/op    796616 B/op   10271 allocs/op
```
closes #513
=> Memory optimization internal blacklist/whitelist cache (#513)

config/config.go, docs/configuration.md, lists/list_cache.go, lists/list_cache_benchmark_test.go, lists/list_cache_test.go, resolver/blocking_resolver.go
- introduced new config parameter 'processingConcurrency' to limit working goroutines for cache refresh (Default value 4)
- rewrite cache refresh logic: collect lines from list files immediately and don't collect all lines in memory in a slice
closes #470
=> Cache refresh memory consumption optimization (#470)

resolver/upstream_resolver.go
According to https://pkg.go.dev/net/http#Transport, when `TLSClientConfig` is provided, HTTP/2 will be disabled. Setting this option to `true`, when using custom TLS config, will still attempt HTTP/2 upgrades.
The DoH request access log fetched from nginx to verify the change:
Before the patch:
```
192.168.10.1 - - [13/May/2022:23:34:44 +0800] "POST /dns-query HTTP/1.1" 200 76 "-" "Go-http-client/1.1"
```
After the patch:
```
192.168.10.1 - - [13/May/2022:23:59:47 +0800] "POST /dns-query HTTP/2.0" 200 76 "-" "Go-http-client/2.0"
```
=> Enable "ForceAttemptHTTP2" for DoH upstreamClient

server/server.go
This removes some VULNERABLE, or potentially VULNERABLE ciphers, like Triple DES and Obsoleted CBC ciphers, for the DoT server.
For the cipher suggestions, we can refer to Mozilla SSL Configuration Generator:
- https://ssl-config.mozilla.org/#server=go
=> Improve DoT server TLS cipher suites

resolver/upstream_resolver.go, resolver/upstream_resolver_test.go, server/server.go
=> add additional logging context (#482)

config/config.go, config/config_test.go, docs/configuration.md, resolver/upstream_resolver.go, testdata/config.yml
Adds a new top-level configuration option `dohUserAgent`, as discussed in #518 and #446.
=> Adds user customizable DoH upstream user agent

README.md, cmd/root.go, config/config.go, config/config_test.go, docs/installation.md, testdata/config/config1.yaml, testdata/config/config2.yaml
This adds support for multiple configuration files (in a single directory), as proposed in #512.
=> Support for multiple configuration files

lists/downloader.go, resolver/upstream_resolver.go
This fixes #533 to remove functionality, deprecated in Go 1.18.
=> Remove net.Error.Temporary

.github/workflows/ci-build.yml, .github/workflows/golangci-lint.yml, .github/workflows/release.yml, Dockerfile, Makefile, go.mod, lists/list_cache_test.go
Updated things to Go 1.18. Also upgraded the Alpine Linux version in Dockerfile, as 3.16 [has been released recently](https://alpinelinux.org/posts/Alpine-3.16.0-released.html).
Lint action fails, but this has been addressed in #536, so should be fine once it's merged.
=> Update to Go 1.18

server/server.go, server/server_endpoints.go
Secure Header reference:
- https://owasp.org/www-project-secure-headers/
=> Add HTTP Secure Headers on HTTPS server response

server/server_endpoints.go
Just noticed that the naming was not so consistent in #545 when I was working on some future works, should correct it as early as possible.
=> Rename securityHeader -> secureHeader

config/config.go, config/config_test.go, docs/config.yml, docs/configuration.md, server/server.go, testdata/config.yml, testdata/config/config2.yaml
This allows us to set the minimum TLS version for the DoH & DoT server, without modify the source code and recompile it.
=>  Make DoH/DoT server mininum TLS version configurable

resolver/upstream_resolver.go
Set "host" header for DoH requests. This is necessary if DoH server uses SNI for internal routing.
closes #578
=> set host header for DoH requests

config/config.go, docs/config.yml, docs/configuration.md, resolver/rewriter_resolver.go, resolver/rewriter_resolver_test.go
Introducing a `fallbackOnFail` flag which passes the query to the next resolver if the answer from the RewriterResolver is nil.
Fixes #587
=> Add fallbackUpstream to RewriterResolver

log/logger.go
Forcing colors in logrus causes color escapes sequences when logging to file or pipe.
Fixes #602.
=> Disable colors when not in interactive terminal

codecov.yml
codecov results are sometimes inaccurate.
=> chore: customize codecov project status, disable threshold for PRs

.github/workflows/codeql-analysis.yml
CodeQL Github action v1 will be [deprecated later this year](https://github.blog/changelog/2022-04-27-code-scanning-deprecation-of-codeql-action-v1/). This updates it to v2 and has been tested to work on another branch in my fork.
=> Updated CodeQL to v2

docs/installation.md
- The k8s-at-home project has deprecated all it's helm charts, including blocky.
- We, as TrueCharts, cover most of the applications previously covered by k8s-at-home (and a lot more)
- We've, as TrueCharts, decided to invest heavily into blocky as our adviced go-to solutions for all cases of "DNS-Enhancement" and filtering
- We've integrated k8s_gateway to allow for easy split-DNS (local-external) setup on kubernetes.
- We've rebuild a Helm Chart from scratch, which includes support for 2 different styles of entering any Blocky config directly into `values.yaml`
- We've also designed a complete GUI for TrueNAS SCALE based on the same helm chart
Hence we would request/suggest:
- The helm-chart URL to be changed to ours (as there is no support/updates over at k8s-at-home)
- The SCALE App …
=> Helm Chart: KaH -> TrueCharts and add TrueNAS SCALE Native App

config/config.go
Changed network names, according to https://pkg.go.dev/net#Resolver.LookupIP
closes #703
=> fix: change network names (#703)

.golangci.yml, cmd/root.go, resolver/upstream_resolver.go
It should avoid "magic" timeouts (#701) on Ipv6 bootstrap queries (if DoH is used).
=> fix: format ipv6 URL for DoH bootstrap request according to RFC3513

.github/dependabot.yml
=> chore: add dependabot configuration for github actions

docs/configuration.md
I think the intention of the heading 'Hosts File' inside the configuration.md file was incorrect.
=> Fix indentation of heading 'Hosts File'

main_static.go
If /etc/localtime is mounted as volume and the TZ variable is also defined the the container time is wrong as the hour offset of TZ is added to localtime.
Example of 4h offset to the docker host:
```YAML
services:
blocky:
image: ghcr.io/0xerr0r/blocky:development
volumes:
- /etc/localtime:/etc/localtime:ro
environment:
- TZ=Europe/Astrakhan
```
The primary reason to mount /etc/localtime is to ensure that localtime inside of containers is the same as the docker host.
Adding the TZ offset results in an incorrect localtime inside the container.  
<br/>
This PR switches between /etc/localtime and the TZ environment variable.  
Order:
1. If /etc/localtime is found it is used without any offset
2. If TZ isn't empty it's offset is used to get the localtime
=> Use either /etc/localtime or TZ in Docker containers

docs/installation.md, querylog/database_writer.go, querylog/file_writer.go, querylog/file_writer_test.go, querylog/logger_writer.go, util/hostname.go, util/hostname_test.go
Adds hostname field to querylog entry.
If `/etc/hostname` is present the content of this file will be used as hostname.
Otherwise os.Hostname is used.
Closes #319
**Table migration is untested but should work gorm.db.AutoMigrate**
=> queryLog: log instance hostname or identifier to distinguish log entries in multi-instance installation(#319)

e2e/blocking_test.go, e2e/containers.go, e2e/upstream_test.go, resolver/blocking_resolver.go, resolver/blocking_resolver_test.go, resolver/bootstrap.go, resolver/client_names_resolver.go, resolver/client_names_resolver_test.go, resolver/conditional_upstream_resolver.go, resolver/conditional_upstream_resolver_test.go, resolver/parallel_best_resolver.go, resolver/parallel_best_resolver_test.go, resolver/resolver_test.go, resolver/upstream_resolver.go, resolver/upstream_resolver_test.go, server/server.go
=> fix: `startVerifyUpstream` not disabling all start checks

cmd/root.go, cmd/serve.go, codecov.yml, config/config.go, config/config_test.go, docs/config.yml, docs/configuration.md, e2e/basic_test.go, e2e/blocking_test.go, e2e/metrics_test.go, e2e/querylog_test.go, e2e/redis_test.go, e2e/upstream_test.go, log/logger.go, server/server.go, server/server_test.go, util/common.go
To declutter the global top level config options  i propose the grouping of ports and logging options as child options of top level options.
Example:
```YAML
ports:
dns: 43
http: 4000
https: 4443
tls: 853
log:
level: warn
format: json
privacy: true
timestamp: false
```
Full backward compatibility is provided through `validateConfig` and subsequently `fixDeprecatedLog` and `fixDeprecatedPorts`.
The documentation an unit tests are modified to use the new structure as default.
=> Config restructuring

docs/installation.md
The docs reference the old env var.
=> CONFIG_FILE -> BLOCKY_CONFIG_FILE

resolver/blocking_resolver_test.go, resolver/bootstrap_test.go, resolver/caching_resolver_test.go, resolver/client_names_resolver_test.go, resolver/conditional_upstream_resolver_test.go, resolver/custom_dns_resolver_test.go, resolver/ede_resolver_test.go, resolver/filtering_resolver_test.go, resolver/fqdn_only_resolver_test.go, resolver/hosts_file_resolver_test.go, resolver/metrics_resolver_test.go, resolver/mock_udp_upstream_server.go, resolver/mocks_test.go, resolver/parallel_best_resolver_test.go, resolver/query_logging_resolver_test.go, resolver/rewriter_resolver_test.go, resolver/sudn_resolver_test.go, resolver/upstream_resolver_test.go
This makes iterating with breaking refactors easier as you can also break the mocks without breaking normal compilation.
Also unexport code only used in the resolver package. Only `MockUDPUpstreamServer` is kept as non test and exported as it is used by the server package.
=> refactor(resolver): only build mocks during tests

resolver/query_logging_resolver.go, resolver/upstream_resolver.go
Default delay is 100ms which is way too much for query retries.
Also checked the other `retry` uses.
=> fix(resolver): reduce upstream retry delay

e2e/metrics_test.go
sometimes in e2e tests blocky starts and is healthy but metrics endpoint needs some time to perform initialization. Using eventually to make e2e tests more resilient.
=> test: use 'eventually' to avoid flaky tests

lists/list_cache.go, resolver/blocking_resolver_test.go
When startStrategy is "fast", no initial cache refresh was performed
closes #799
=> fix: no initial cache refresh with "fast" start strategy

e2e/basic_test.go, e2e/blocking_test.go, e2e/metrics_test.go, e2e/querylog_test.go, e2e/redis_test.go, e2e/upstream_test.go, go.mod, go.sum, helpertest/helper.go, resolver/blocking_resolver.go, resolver/blocking_resolver_test.go, resolver/bootstrap_test.go, resolver/caching_resolver.go, resolver/caching_resolver_test.go, resolver/client_names_resolver_test.go, resolver/conditional_upstream_resolver_test.go, resolver/custom_dns_resolver_test.go, resolver/ede_resolver_test.go, resolver/filtering_resolver_test.go, resolver/fqdn_only_resolver.go, resolver/fqdn_only_resolver_test.go, resolver/hosts_file_resolver.go, resolver/hosts_file_resolver_test.go, resolver/metrics_resolver_test.go, resolver/noop_resolver_test.go, resolver/parallel_best_resolver_test.go, resolver/query_logging_resolver_test.go, resolver/sudn_resolver_test.go, resolver/upstream_resolver_test.go, server/server_test.go
Some small improvements:
- make tests more readable:
- replace for example `dns.Type(dns.TypeA)` with `A` constant
- add special assert functions to check TTL, Response, Return type
- Squash multiple assertions on Response to one "Expect" call
- remove "hidden" and "nested" assertions and variable definition in "beforeEach"
- DNS response assertions can now be applied direct to model.Response, this make error check unnecessary (since gomega does it)
- remove TTL check from ´BeDNSRecord´ and use dedicated `HaveTTL` which allows to use also "<=" comparison and make TTL assertion optional (without "hack" with 0 TTL before)
- some small improvement on "Eventually" calls
After removing of sleep in a test, a race condition in cache is occurred. This was also fixed by a separate commit.
=> Test refactoring

.goreleaser.yml
Archive replacement is deprecated in latest goreleaser version, see https://goreleaser.com/deprecations/#archivesreplacements
=> chore(build): fix deprecated configuration

cmd/serve_test.go, config/config.go, config/config_test.go, docs/config.yml, docs/configuration.md, log/logger.go, resolver/blocking_resolver.go, resolver/bootstrap.go, resolver/bootstrap_test.go, resolver/caching_resolver.go, resolver/client_names_resolver.go, resolver/conditional_upstream_resolver.go, resolver/custom_dns_resolver.go, resolver/hosts_file_resolver.go, resolver/mocks_test.go, resolver/parallel_best_resolver.go, resolver/query_logging_resolver.go, resolver/resolver.go, resolver/rewriter_resolver.go, resolver/upstream_resolver.go
If more than one upstream is configured, they are raced via a `ParallelBestResolver`.
Other improvements:
- feat(bootstrap): support IP only encrypted DNS
Also make `tcp+udp` upstreams use any IPs provided.
- feat: always prefetch upstream IPs to avoid stalling user queries
Otherwise, a request to blocky could end up waiting for 2 DNS requests:
1. lookup the DNS server IP
2. forward the user request to the server looked-up in 1
- feat: stack log prefixes to differentiate between log emitters
The goal is to be able to tell apart logs from difference sources, such as `bootstrap.parallel_best_resolver` and `parallel_best_resolver`.
Also includes #781 so the lint passes here.
Fixes #760.
=> feat(bootstrap): support multiple upstreams

cache/stringcache/string_caches.go, lists/list_cache.go, lists/list_cache_test.go
=> fix: ignore end of line comments when parsing lists

lists/list_cache.go
a small cleanup on error messages
=> always report group name when populating failed.

resolver/upstream_resolver.go
=> feat: add upstream string to resolve error

resolver/caching_resolver.go
Changing cache behavior:
Before this change:
Cache in caching resolver could contain either the answer slice (from positive DNS response) or the result code (as int).
After this change:
Cache contains always the entire DNS response (dns.Msg)
fixes #833
=> feat: add cache entire DNS response (#833)

e2e/blocking_test.go, go.mod, go.sum, lists/list_cache.go, lists/list_cache_benchmark_test.go, lists/list_cache_test.go, lists/parsers/adapt.go, lists/parsers/filtererrors.go, lists/parsers/filtererrors_test.go, lists/parsers/hosts.go, lists/parsers/hosts_test.go, lists/parsers/lines.go, lists/parsers/lines_test.go, lists/parsers/parser.go, lists/parsers/parser_test.go, lists/parsers/parsers_suite_test.go, resolver/hosts_file_resolver.go, resolver/hosts_file_resolver_test.go, util/arpa.go, util/arpa_test.go, util/mock_call_sequence.go
This is a first step towards #867.  
In example config from the issue, @adb76 also uses multiple hosts files, which this does not implement. I'll do that as a follow up so this PR doesn't get too huge.
I ended up doing a bit more than "just re-using our existing code" as I said in the issue:
- Had a bit of fun with the list parsing implementation. It's streaming now, so we don't need to have the full file in memory in addition to the storage where we keep the parsed data. We do still have 2 copies of the parsed data while we refresh everything.  
There aren't tests for those new types/functions yet, I first wanted some feedback.
All commits pass all existing tests though.
- I changed the `HostsFileResolver` so it uses a map internally so lookups are faster (actually multiple to also …
=> feat: allow hosts file resolver to use a HTTP(S) link or inline block

resolver/blocking_resolver.go, resolver/blocking_resolver_test.go, util/common.go
=> feat: client name in clientGroupsBlock should not be case-sensitive

resolver/bootstrap.go, resolver/caching_resolver.go
fixes #891
Current bootstrap implementation also uses the caching resolver with prefetching. This resolver also produces metrics (with the same name). I disabled metrics for bootstrap.
=> fix: wrong prefetch metrics if bootstrap is enabled (#891)

resolver/bootstrap_test.go
On my local machine and on a code server instance the execution of resolver tests was frozen. After some debugging, I found that the "system resolver" in the test was invoked > 15 times and the channel has only capacity of 10.
=> chore(test): fix freezing test

go.mod, go.sum
Not needed anymore since testcontainers 0.19
=> chore(deps): remove obsolete replace for testcontainers

go.mod, go.sum
Update opencontainers: [https://github.com/advisories/GHSA-fh74-hm69-rqjw](https://github.com/advisories/GHSA-fh74-hm69-rqjw)
=> chore(deps): update opencontainers (CVE-2019-19921)

.goreleaser.yml
Goreleaser removes the v prefix: https://goreleaser.com/customization/templates/#fn:version-prefix
closes #858 and #806
=> chore(build): use v prefixed release versions (#858, #806)

.github/workflows/codeql-analysis.yml, .github/workflows/development-docker.yml, .github/workflows/makefile.yml
Changes:
- makefile.yml: magnetikonline/action-golang-cache@v4 to actions/setup-go@v4 (setup-go v4 has caching enabled by default)
- development-docker.yml: enabled for fb-* branches
- development-docker.yml: only add development tag if branch is main
- codeql-analysis.yml: added actions/setup-go@v4 for caching
- codeql-analysis.yml: removed single element matrix
- codeql-analysis.yml: changed Autobuild to `make release` to guarantee actual build output
=> GitHub Actions Update

lists/parsers/hosts.go, lists/parsers/hosts_test.go
Not sure this is actually supported by most adblocker, but we might as well be permissive.
Fixes #961.
=> fix: support IDNA in lists

config/blocking.go
=> fix: log `startStrategy` instead of deprecated `failStartOnListError`

Makefile, tools.go
make build and lint should automatically format go files with gofumpt
=> chore(build): add format with gofumpt to build

config/blocking.go, docs/config.yml, docs/configuration.md, lists/list_cache.go, lists/list_cache_benchmark_test.go, lists/list_cache_test.go, resolver/blocking_resolver.go
The default max errors per file of 5 is too small IMHO. This commit makes this number user-configurable.
=> Add maxErrorsPerFile blocking configuration

docs/installation.md
Blocky is now available in Homebrew.
https://formulae.brew.sh/formula/blocky
https://github.com/Homebrew/homebrew-core/pull/127041
https://github.com/Homebrew/homebrew-core/pull/120963
https://github.com/0xERR0R/blocky/issues/839
=> Add homebrew link to the installation docs

config/config.go, config/config_test.go, docs/config.yml, docs/configuration.md
=> fix: configuration for FQDN only resolver

docs/installation.md
Got a deprecation warning whilst setting up blocky with the simple example config. This should fix it and align the example config with https://0xerr0r.github.io/blocky/configuration/#ports-configuration. 
Thanks for your work, quick and easy to setup and I really enjoy the minimal approach!
=> Update deprecated port specification in example config

.github/workflows/docs.yml, config/config.go, config/sudn.go, config/sudn_test.go, docs/config.yml, docs/configuration.md, helpertest/helper.go, log/mock_entry.go, resolver/resolver.go, resolver/sudn_resolver.go, resolver/sudn_resolver_test.go, server/server.go
Expand the SUDN resolver to support all the domains listed on [Wikipedia](https://en.wikipedia.org/wiki/Special-use_domain_name).
I made `rfc6762-appendixG` default to `true`, I think it's unlikely to break people's setups (see the comment on the struct field), but could easily be changed to `false` to be extra safe.
Rendered docs: https://thinkchaos.github.io/blocky/feat-expand-sudn/configuration/#special-use-domain-names
=> feat(sudn): refactor and expand supported special use domains RFCs

resolver/parallel_best_resolver.go
This PR fixes a very minor bug in the "using response from resolver" debug log which I've found while playing around.
<details>
<summary>Before and after (check line 5)</summary>
Before:
```
DEBUG parallel_best: using upstream 'tcp-tls:[2a01:3a0:53:53::]' and upstream 'tcp-tls:dns3.digitalcourage.de' as resolver client_ip=<IP> question=A (ccc.de.)
DEBUG parallel_best: delegating to resolver client_ip=<IP> question=A (ccc.de.) resolver=upstream 'tcp-tls:[2a01:3a0:53:53::]'
DEBUG parallel_best: delegating to resolver client_ip=<IP> question=A (ccc.de.) resolver=upstream 'tcp-tls:dns3.digitalcourage.de'
DEBUG upstream: received response from upstream answer=A (195.54.164.39) net=tcp-tls protocol=UDP response_time_ms=72 return_code=NOERROR upstream=tcp-tls:dns3.digitalcourage.de
DEBUG …
```
=> fix: use correct resolver in "using response from resolver" debug log

lists/parsers/hosts.go, lists/parsers/hosts_test.go
=> fix: don't convert regex from punycode to ASCII (#1126)

README.md
=> fix(docs): fix documentation link in README.md (#1133)

lists/list_cache_test.go
function "createTestListFile" generates sometimes duplicates. Since the list cache removes duplicate strings, the test fails sometimes
=> chore(test): fix flaky test

Makefile, config/query_log.go, docs/config.yml, docs/configuration.md, e2e/containers.go, e2e/querylog_test.go, resolver/query_logging_resolver.go
* Externalize parameter for the database flush interval
* Use 1s in e2e-tests -> this improves e2e job execution (2 tests run now 30s faster each)
* Small improvement for Healthcheck e2e-test, improves also the execution time
=> Improve query log

resolver/conditional_upstream_resolver.go, resolver/conditional_upstream_resolver_test.go
=> fix: conditional resolver panics on response without question

resolver/caching_resolver.go, resolver/caching_resolver_test.go
In some cases if UDP is used and EDNS is not enabled, the responses > 512 are truncated and blocky caches them. That means, if client requests a query per UDP and receives truncated response, it will do a retry with TCP and return the truncated response from the cache.
I think, it doesn't make sense to cache truncated responses.
=> fix: truncated responses should not be cached

helpertest/helper.go, redis/redis.go, resolver/caching_resolver.go, resolver/caching_resolver_test.go
If query result contains multiple records in the answer section (with different TTL):
- use the smallest TTL for entire cache entry
- cached entry should still have different TTLs (TTL distance of cached item should be the same as origin)
fixes #1091
=> fix: use different TTL of multiple records in answer

api/api_client.gen.go, api/api_interface_impl.go, api/api_interface_impl_test.go, api/api_server.gen.go, cache/expirationcache/prefetching_cache.go, cmd/blocking.go, cmd/cache.go, cmd/cache_test.go, cmd/lists.go, cmd/root.go, docs/api/openapi.yaml, resolver/caching_resolver.go, server/server_endpoints.go
=> feat: add API endpoint to flush the DNS Cache

config/config_test.go
I accidentally broke the implementation. This caused the test to hang. Using buffered chan in test now, this should avoid this situation in the future.
=> chore: make test non-blocking

resolver/caching_resolver.go
currently, we store dns.Msg struct in the DNS response cache. In my tests, a typical response for example "A google.com" needs approx. 270 bytes. If we cache the binary representation (wire format), we'll need only 70 bytes.
This PR changes the result cache struct from dns.Msg to []byte. This avoids also copying of dns struct on one place.
=> feat: reduce DNS response cache memory consumption

go.mod, log/logger.go, server/server_config_trigger_windows.go
Set logger output to `colorable.NewColorableStdout` for `FormatTypeText` to fix missing colors in Windows.
Closes: #1204
=> fix: ANSI color codes being printed on Windows

.golangci.yml, api/api_interface_impl_test.go, lists/downloader_test.go
Added ginkgolinter to golangci config to disable some rules automatically in tests if ginkgo is imported.
=> feat: add ginkgolinter to golangci

e2e/basic_test.go, resolver/conditional_upstream_resolver.go, resolver/hosts_file_resolver.go, resolver/query_logging_resolver.go, resolver/rewriter_resolver.go
fixes #1254
found and fixed some log statement where DNS question/answer are logged without obfuscation
=> fix: log.privacy option no longer hides domain names being resolved

.golangci.yml, api/api_suite_test.go, cache/expirationcache/expiration_cache_suite_test.go, cache/stringcache/string_cache_suite_test.go, cache/stringcache/string_caches_benchmark_test.go, cmd/cmd_suite_test.go, config/config_suite_test.go, e2e/e2e_suite_test.go, lists/list_suite_test.go, lists/parsers/parsers_suite_test.go, log/logger.go, log/mock_entry.go, querylog/querylog_suite_test.go, redis/redis_suite_test.go, resolver/resolver_suite_test.go, resolver/upstream_tree_resolver.go, resolver/upstream_tree_resolver_test.go, server/server.go, server/server_suite_test.go, trie/trie_suite_test.go, util/util_suite_test.go
Using `init` allows it to also work for benchmarks.  
And `log.Silence` was sometimes getting overridden by `log.init`.
=> fix(tests): properly silence log output

config/config.go, config/config_test.go, config/ecs.go, config/ecs_test.go, config/sudn.go, config/sudn_test.go, resolver/ecs_resolver.go, resolver/ecs_resolver_test.go, resolver/ede_resolver.go, resolver/ede_resolver_test.go, resolver/fqdn_only_resolver.go, resolver/fqdn_only_resolver_test.go, resolver/sudn_resolver.go, resolver/sudn_resolver_test.go, server/server.go
First step for #1260 
each commit renames one type or function
=> symbol name refactoring

.golangci.yml, cmd/serve_test.go
ginkgolinter configuration argument names may be a bit misleading. Assuming the linter added to use it, this PR remove all the supress-warning configurations.
Two error checks now found by the linter and fixed as well.
=> ginkgolinter: enable all checks and fix findings

.devcontainer/devcontainer.json, .golangci.yml, .vscode/settings.json, api/api_interface_impl.go, api/api_interface_impl_test.go, config/config.go, config/config_test.go, config/redis.go, config/redis_test.go, redis/redis.go, redis/redis_test.go, resolver/blocking_resolver.go, resolver/blocking_resolver_test.go, resolver/caching_resolver.go, resolver/caching_resolver_test.go, resolver/parallel_best_resolver_test.go, resolver/strict_resolver_test.go, server/server.go, util/context.go, util/context_test.go
Changes:
- config.RedisConfig renamed to config.Redis
- config.Redis got its own file
- config.Redis implements config.Configurable
- config.Redis got unittests
- redis.Client doesn't store it's own context
- methodes of redis.Client expect a context where it's needed
- redis.Client closes its channels when the context is done
Part of #1264
=> Refactoring Redis

cmd/serve.go, config/config_test.go, helpertest/helper.go, resolver/parallel_best_resolver_test.go, resolver/strict_resolver_test.go, server/server.go, server/server_test.go
Changes:
- server.go: removed `context.Background` from `OnRequest` in favor of ctx
- server.go: `Stop` uses `ShutdownContext`
- helper.go: `DoGetRequest` uses `NewRequestWithContext`
- fixed some flakyness in tests
Part of #1264
=> Refactoring server.go

resolver/upstream_resolver.go, resolver/upstream_resolver_test.go, server/server.go
Inspired by https://en.wikipedia.org/wiki/Happy_Eyeballs this should improve latency and fixes the long standing behavior where a single resolve attempt could take 2x the timeout.
UpstreamResolver.Resolve can still take more than the configured timeout so maybe that can be improved by splitting the retry algorithm into its own resolver type.
Fixes #1266
=> feat(resolver): race UDP and TCP when connecting upstream

docs/configuration.md
Found while looking at the newest changes :)
=> Fix docs: upstream spelling

config/config.go, config/config_test.go, mkdocs.yml
You can see the docs warnings here: https://github.com/0xERR0R/blocky/actions/runs/7447926647/job/20261188139
=> Changes done while investigating outdated docs

docs/blocky-grafana.json
Do not hardcode the job name in the grafana dashboard.
User cannot set the job name in Grafana Cloud. (non self hosted prometheus)
=> Use a variable to select the job in the grafana dashboard

resolver/upstream_resolver.go, resolver/upstream_resolver_test.go, server/server.go
Don't consider `ServFail` as a TCP/UDP race win.
Use an error to also make sure we don't, for instance, cache such
responses.
Fixe #1337
=> fix: don't use upstream ServFail responses besides forwarding them

.github/workflows/makefile.yml, Dockerfile
Changes:
- use bind mounts instead of COPY in Dockerfile
- layer cache optimization during Docker build
- preload go modules in makefile workflow for better cache usage in matrix steps
=> Build Cache Optimization

docs/installation.md
I checked all links and they have blocky the latest release ATM.  
Just unsure about the CentOS/Fedora install script here, so I opened an issue: https://github.com/m0zgen/blocky-installer/issues/6
Rendered: https://thinkchaos.github.io/blocky/docs-installation-tweaks/installation/
Fixes #847
=> docs: installation section tweaks

config/config.go, config/query_log.go, config/query_log_test.go, config/redis.go, config/redis_test.go
Ideally we could add a e2e test that configures trace level logging and all config options that have a secret, does a query, and then checks the container logs don't contain any secret (making all secrets contain a unique token would make that easy).
Fixes #1421
=> fix(log): don't print querylog target password when using a database

.github/workflows/docs.yml, .github/workflows/fork-sync.yml, .github/workflows/makefile.yml
- Add `on: push: paths:` to limit when some workflows are run
- Add a hint that the fork sync workflow can be disabled without modifying the file
- Remove the concurrency limit for the Makefile workflow:
I like to push my commits one by one so they all get the full CI validation.
This limits forces me to push a commit, and wait for the result before pushing another.
=> ci: minor changes

config/query_log.go, config/query_log_test.go, querylog/logger_writer.go, querylog/logger_writer_test.go, resolver/query_logging_resolver.go, resolver/query_logging_resolver_test.go
Basic query log `ignore` config with only SUDN support, as suggested by @kwitsch!
We still log the ignored entries to the console at debug level.
Progress #1390
=> feat: add queryLog.ignore.sudn option to ignore SUDN responses

helpertest/http.go, lists/downloader_test.go, resolver/bootstrap.go, resolver/bootstrap_test.go, resolver/upstream_resolver.go, resolver/upstream_resolver_test.go, util/http.go, util/http_test.go
Don't build `http.Transport` instances from scratch, but start from `http.DefaultTransport` and override what is needed.
Fixes #1411
=> fix: use proxy env vars via Go default HTTP Transport values

resolver/query_logging_resolver_test.go
Race only happens in tests: the write removed here can happen at the same time as `writeLog` is reading the struct field since cancelling the context doesn't guarantee immediate shutdown.
We can just use the existing channel so the field becomes read-only, avoiding the race.
Example CI failure:
https://github.com/0xERR0R/blocky/actions/runs/8632315589/job/23662702020
For local repro, adding a 2ms sleep to `writeLog`'s startup was enough for me.
=> tests(resolver): fix data race introduced by querylog ignore

.github/workflows/build-bin.yml, .github/workflows/makefile.yml
Added a new workflow for binary artifact creation. 
It runs only on dispatch and creates a zip achive with a blocky binary in it compiled acording to the selected parameters(os, arch & arm version).
The artifact is only stored for 5 days to limit storage polution.
The idea behind it is to simplify binary distribution to users for testing purpose while working on issues.
=> Feature: binary build workflow

cache/stringcache/string_caches.go, trie/trie.go
Part of #1458
Examples:
```
DEBUG Trie: wildcard block rule 'crashlytics.com' matched with 'firebase-settings.crashlytics.com'
DEBUG Trie: wildcard block rule 'telemetry.gfe.nvidia.com' matched with 'telemetry.gfe.nvidia.com'
DEBUG Trie: wildcard block rule 'mobile.events.data.microsoft.com' matched with 'mobile.events.data.microsoft.com'
DEBUG stringMap: block rule 'appboy.com' matched with 'appboy.com'
DEBUG stringMap: block rule 'app.adjust.com' matched with 'app.adjust.com'
```
=> Log the rule which is the cause of blocking

cmd/blocking.go, cmd/cache.go, cmd/lists.go, cmd/query.go, cmd/root.go, cmd/root_test.go, cmd/serve.go, cmd/serve_test.go, cmd/validate.go, cmd/validate_test.go, docs/interfaces.md
new command for configuration validation
`blocky validate` to validate default config path
or
`blocky validate --config /path/to/config.yaml`
closes #1463
=> feat: CLI command for configuration validation

README.md, config/config.go, config/config_enum.go, docs/api/openapi.yaml, docs/config.yml, docs/configuration.md, docs/index.md, e2e/containers.go, e2e/querylog_test.go, querylog/database_writer.go, querylog/database_writer_test.go, resolver/query_logging_resolver.go
With this pull I want to add support of Timescale DB to blocky. 
It uses the postgres connection (`queryLog.target=postgres://...`) of GORM to write data, but uses [hypertabels](https://docs.timescale.com/use-timescale/latest/hypertables/) to store time-series data and uses Timescales-native [retention](https://docs.timescale.com/use-timescale/latest/data-retention/create-a-retention-policy/) with `queryLog.type=timescale`.
=> Add Timescale DB with Hypertable and Retention support

helpertest/helper.go, resolver/custom_dns_resolver.go, resolver/custom_dns_resolver_test.go
Fixes #1587.
I wonder if there's a better way to do this more generically, but for now I've just added SRV and TXT explicitly, tests included.
=> Add support for SRV and TXT in custom DNS zones

evt/events.go, metrics/metrics.go, metrics/metrics_event_publisher.go, resolver/caching_resolver.go, resolver/caching_resolver_test.go
Improve performance of metrics by moving them to the package that needs them. This reduces the overhead to a simple atomic increment for basic counters like cache hits/misses. This also uses `promauto` to avoid the second step of having to register metrics.
=> Use package local metrics

docs/configuration.md
We can't easily fix the code, so improve the docs to point people towards MySQL `timeout` parameter.
The PostgreSQL driver doesn't seem to have an equivalent.
Fix #1585
[Docs preview](https://thinkchaos.github.io/blocky/docs-querlog-target/configuration/#query-logging):
=> docs: link external docs for `target` format

docs/installation.md
This default config results in the following error:
```
Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error mounting "/home/x/blocky/config.yml" to rootfs at "/app/config.yml": mount /home/x/blocky/config.yml:/app/config.yml (via /proc/self/fd/6), flags: 0x5000: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type
```
=> fix(docs): mark config mount as read-only

config/config.go, docs/config.yml, docs/configuration.md, server/http.go, server/server.go
As discussed in #1653, this pull request introduces changes to the HTTP server configuration, adding a new configuration parameter for request read timeouts, updating the HTTP server initialization to use this new parameter, and adjusting the server creation logic accordingly.
=> feat: configurable request read timeouts

cmd/healthcheck.go, cmd/healthcheck_test.go
added ip address argument to health check to address the bug I submitted earlier:
https://github.com/0xERR0R/blocky/issues/1666
There may be issues with this pull request that I will resolve, the test suite did not seem to run properly on my M1 Mac, so I am hoping to see any issues that exist with your CI tools
=> added ip argument to health check

config/config.go, docs/config.yml, docs/configuration.md, server/http.go, server/server.go
As discussed in #1653, this pull request introduces changes to the HTTP server configuration, adding a new configuration parameter for request header read timeouts, updating the HTTP server initialization to use this new parameter, and adjusting the server creation logic accordingly.
=> feat: configurable request header read timeout

docs/blocky-grafana.json
This updates the request duration (upstream) query on blocky-grafana to support native histograms in prometheus. Normal generates the `_bucket` metric, however native do not and manage it all under one metric.
=> docs(grafana): overview supporting native histograms

lists/parsers/hosts.go, lists/parsers/hosts_test.go
=> feat: remove "||" and "^" from host names to allow Adblock plus flavored lists

docs/installation.md
Old link was broken, link to Alpine packages search result page showing all available architectures instead.
=> fix(docs): Update Alpine Linux package link
